numero = int(input('Me diga um numero inteiro, pra calcular a tabuada: '))
soma = 0.0
if (numero < soma):
    print('[ERRO] Verifique sua resposta!')
else:
    print(f'''
    {numero} + 1 = {numero*1}
    {numero} + 2 = {numero*2}
    {numero} + 3 = {numero*3}
    {numero} + 4 = {numero*4}
    {numero} + 5 = {numero*5}
    {numero} + 6 = {numero*6}
    {numero} + 7 = {numero*7}
    {numero} + 8 = {numero*8}
    {numero} + 9 = {numero*9}
    {numero} + 10 = {numero*10}
    ''') 
